// ============================================================
// 2D 粒子 .plist 导出 + Shader .effect 导出 + AnimationClip 导出
// ============================================================
import type { Particle3DConfig } from '@/types/effect';
import { generateUUID } from './effect-defaults';

export function generatePlist(config: Particle3DConfig, name: string): string {
  const m = config.mainModule;
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>angle</key><real>0</real>
  <key>angleVariance</key><real>${(m.startRotation3D?.x?.constant ?? 0) * 10}</real>
  <key>blendFuncDestination</key><integer>771</integer>
  <key>blendFuncSource</key><integer>1</integer>
  <key>duration</key><real>${m.duration}</real>
  <key>emitterType</key><integer>0</integer>
  <key>finishColorAlpha</key><real>${m.startColor.keys[m.startColor.keys.length-1]?.color[3] ?? 0}</real>
  <key>finishColorBlue</key><real>${m.startColor.keys[m.startColor.keys.length-1]?.color[2] ?? 0}</real>
  <key>finishColorGreen</key><real>${m.startColor.keys[m.startColor.keys.length-1]?.color[1] ?? 0}</real>
  <key>finishColorRed</key><real>${m.startColor.keys[m.startColor.keys.length-1]?.color[0] ?? 1}</real>
  <key>finishParticleSize</key><real>${(m.startSize3D?.x?.constant ?? 1) * 0.5}</real>
  <key>gravityx</key><real>0</real>
  <key>gravityy</key><real>${m.gravityModifier * 100}</real>
  <key>maxParticles</key><integer>${m.capacity}</integer>
  <key>maxRadius</key><real>${config.shapeModule.radius * 10}</real>
  <key>maxRadiusVariance</key><real>0</real>
  <key>minRadius</key><real>0</real>
  <key>particleLifespan</key><real>${m.startLifetime.constant ?? 2}</real>
  <key>particleLifespanVariance</key><real>${m.startLifetime.mode === 'randomBetween' ? ((m.startLifetime.max ?? 3) - (m.startLifetime.min ?? 1)) / 2 : 0}</real>
  <key>radialAcceleration</key><real>0</real>
  <key>radialAccelVariance</key><real>0</real>
  <key>rotatePerSecond</key><real>0</real>
  <key>rotatePerSecondVariance</key><real>0</real>
  <key>rotationEnd</key><real>0</real>
  <key>rotationStart</key><real>0</real>
  <key>sourcePositionx</key><real>0</real>
  <key>sourcePositiony</key><real>0</real>
  <key>sourcePositionVariancex</key><real>${config.shapeModule.radius * 5}</real>
  <key>sourcePositionVariancey</key><real>${config.shapeModule.radius * 2}</real>
  <key>speed</key><real>${m.startSpeed.constant ?? 5}</real>
  <key>speedVariance</key><real>${m.startSpeed.mode === 'randomBetween' ? ((m.startSpeed.max ?? 8) - (m.startSpeed.min ?? 3)) / 2 : 1}</real>
  <key>startColorAlpha</key><real>${m.startColor.keys[0]?.color[3] ?? 1}</real>
  <key>startColorBlue</key><real>${m.startColor.keys[0]?.color[2] ?? 1}</real>
  <key>startColorGreen</key><real>${m.startColor.keys[0]?.color[1] ?? 1}</real>
  <key>startColorRed</key><real>${m.startColor.keys[0]?.color[0] ?? 1}</real>
  <key>startParticleSize</key><real>${m.startSize3D?.x?.constant ?? 1}</real>
  <key>startParticleSizeVariance</key><real>0</real>
  <key>tangentialAcceleration</key><real>0</real>
  <key>tangentialAccelVariance</key><real>0</real>
  <key>textureFileName</key><string>${name}.png</string>
</dict>
</plist>`;
}

export function generateEffectFile(name: string, shaderCode: string, uuid?: string): string {
  const id = uuid || generateUUID();
  const header = `// Cocos Creator 3.8 Effect File
// Generated by Cocos AI Effect Generator
// UUID: ${id}

`;
  if (shaderCode.includes('CCEffect')) {
    return shaderCode.includes(`UUID: ${id}`) ? shaderCode : `${header}${shaderCode}`;
  }
  return `${header}${shaderCode}

// Metadata
// name: ${name}
// uuid: ${id}
// version: 1.0.0
`;
}

export function generateAnimationClip(name: string, tracks: any[], duration: number): string {
  const uuid = generateUUID();
  return JSON.stringify({
    __type__: 'cc.AnimationClip',
    _name: name,
    _objFlags: 0,
    _duration: duration,
    sample: 60,
    speed: 1,
    wrapMode: 2,
    curveData: {
      comps: {},
      paths: tracks.reduce((acc: any, t: any) => {
        acc[t.property] = {
          keys: t.keyframes.map((k: any) => ({
            frame: Math.round(k.time * duration * 60),
            value: k.x ?? k.y ?? k.scaleX ?? k.opacity ?? 0,
            easingData: []
          }))
        };
        return acc;
      }, {})
    },
    _native: '',
    _id: uuid
  }, null, 2);
}
